### ISSUE TITLE
 lucky dev always listen on localhost:3000 on my linux laptop.

### ISSUE THREAD

**Issue by zw963** [luckyframework/website#1180]
I don't know why, when following setup in the README, but the server always listen on 3000 when run `lucky dev`.

In fact,  i couldn't following the document in [beginners tutorials](https://github.com/luckyframework/website/blob/main/src/actions/guides/tutorial/00_overview.cr#L139) too, the document said the clover project will listen on localhost:3001, but i listen on localhost:3000 too.

So, i guess maybe somewhere is misconfigured, how to figure it out?

I haven't checked the source code of how `lucky dev` works, is there a way to change the port to make several project can be running synchronously?

Thanks.

----------

I found i can change `config/watch.yml` to achieve this, is there something wrong?

**Comment by jwoertink** [comment]
It looks like when we made the change, we never updated the docs. You are correct, to change it you update the `config/watch.yml` or you can set the `DEV_PORT` ENV. 

We need to update the guides to make sure this is clear :+1:

**Comment by zw963** [comment]
We need update README too.

https://github.com/luckyframework/website/blob/main/README.md?plain=1#L11

**Comment by jwoertink** [comment]
I updated that.

**Comment by zw963** [comment]
> or you can set the DEV_PORT ENV.

Hi, find another one issue, when set DEV_PORT to 3002 in the .env, the listen port is changed. but, the happy message output when running `lucky dev` still told me, i am listen on 3000

```
🎉 App running at http://127.0.0.1:3000
```

**Comment by jwoertink** [comment]
I opened an issue for that here https://github.com/luckyframework/lucky/issues/1874
