### ISSUE TITLE
 algolia misconfigured keys in app.js 

### ISSUE THREAD

**Issue by 367null** [luckyframework/website#1201]
I was reading the javascript source and i found API keys from algolia that happens to be misconfigured

located at : https://github.com/luckyframework/website/blob/main/src/js/app.js
& : https://luckyframework.org/js/app.js

![do](https://user-images.githubusercontent.com/40462602/236187310-17c13241-76a0-4429-9de3-f94d51223544.png)
Xalglia Scanner : https://github.com/dsweb19778/xgolia

simply allow only search

**Comment by jwoertink** [comment]
Do you know what is misconfigured? I got that config right from Algolia, and the search is working, so I'm not sure what I'd need to change.
