### ISSUE TITLE
validating-saving.cr - before custom_validation

### ISSUE THREAD

**Issue by ghost** [luckyframework/website#127]
Hello there,

I am not really facing an issue, so forgive me if I missed something. It is pretty minor.

I am writing a `Save::Operation` in which I want to validate an e-mail address. Following the example:
https://github.com/luckyframework/website/blob/d56ea7f43f5cce7a23776f282eef91fea0afc341/src/actions/guides/database/validating-saving.cr#L339
, I would write it like this:

```ruby
before validate_email

private def validate_email
  # ... some implementation
end
```

But then I get the following error: `Error: undefined local variable or method 'validate_email' for SaveUser.class`. Could it be that the `before_save`-hook should be used?

```ruby
# before validate_email
before_save validate_email
```

**Comment by paulcsmith** [comment]
Yes that is correct! It should be “before_save”

We can add a compile time error for “before” that tells people to use “before_save”

Let me know if you have any other questions

**Comment by paulcsmith** [comment]
Also we need to update the guide. Thanks for pointing that out! I didn’t realize this was in the website repo when I first saw it

**Comment by ghost** [comment]
Great, thanks for your response! I'll let you guys know if I come across anything :)
