### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website#19]

**Comment by jwoertink** [comment]
Some things the footer had previously:
* Github link (icon)
* Twitter link (icon)
* Gitter link (icon)
* Link to Code of Conduct
* Link and mention of contributors

**Comment by robertguss** [comment]
I can try and tackle this PR if you would like, I am a front-end dev. A couple of questions though:
- Where can I find the links to the Code of Conduct and contributors?
- by adding a twitter link & icon will that resolve issue #28? if not, let me know where you would like an additional Twitter link.

**Comment by paulcsmith** [comment]
Hey @robertguss! This would be wonderful. 

* Contributors: https://github.com/luckyframework/lucky/graphs/contributors
* Code of conduct: https://github.com/luckyframework/lucky/blob/master/CODE_OF_CONDUCT.md

And yes I think that'd resolve #28. I may want to add it somewhere else too but the footer is a great start.

**Comment by robertguss** [comment]
@paulcsmith having an issue when I run up:

```
Error in src/start_server.cr:1: while requiring "./app"
app_1     |
app_1     | require "./app"
app_1     | ^
app_1     |
app_1     | in src/app.cr:27: while requiring "../config/**"
app_1     |
app_1     | require "../config/**"
app_1     | ^
app_1     |
app_1     | in config/database.cr:3: Avram::Repo has been renamed to Avram::Database and requires a subclass now.
app_1     |
app_1     | Try this...
app_1     |
app_1     |   1. Create a database class called 'AppDatabase' that inherits from 'Avram::Database'
app_1     |   2. Configure it with 'AppDatabase.configure'
app_1     |   3. Set the database in 'BaseModel' (can also be specific per model). Example:
app_1     |
app_1     |       class BaseModel < Avram::Model
app_1     |         def self.database
app_1     |           AppDatabase
app_1     |         end
app_1     |       end
app_1     |
app_1     |
app_1     | Avram::Repo.configure do |settings|
app_1     |             ^~~~~~~~~
app_1     |
app_1     | There was a problem compiling. Watching for fixes...
```

is this because I am using lucky v0.17.0-rc1? should I use v0.16.0? if so can I specify a specific version in the docker file?

**Comment by jwoertink** [comment]
hey @robertguss thanks for tackling this. Here's the PR I did for the footer on the old site https://github.com/luckyframework/website-old/pull/212 you can use for reference..

Also, as for that error, yes, this app hasn't really been updated for 0.17 support just yet. Try using 0.16 if you can.

**Comment by robertguss** [comment]
I spent a couple hours yesterday trying to get the website/app working both with docker and without and kept running into various errors. Is there a branch that is configured to work with 0.16 that I could pull down? If not do you think a new branch could be configured to make it easy for newbies like me to contribute? Sorry but I am just getting started with Lucky.

**Comment by jwoertink** [comment]
Sorry for the issues. It's probably because we always point to master branch on everything, so it makes it a little tough sometimes. 

I'll take a look at upgrading this app to ensure it's fully 0.17 supported. Once that's merged in, then you will be able to rebase from master and hopefully everything will just work for you. I'll let you know when you should be good.

**Comment by robertguss** [comment]
Thank you.

**Comment by jwoertink** [comment]
@robertguss ok, rebase, and give it another shot. You may need to clear out some docker cache stuff. For example, I had to 

* `up down` - ensure the docker container is stopped
* `docker image prune` - remove some images I wasn't using
* `docker container prune` - remove some containers I'm not using
*  `rm up.cache` - tell up to not use cache

You may not need to do those, but just in case you run in to a weird cache issue, it may help.

**Comment by robertguss** [comment]
Still can't get it to work with Docker or Up, but I managed to get it working locally on my mac. Good to go now.

Thank you for updating and configuring everything. I will get to work on the footer asap.

**Comment by jwoertink** [comment]
Weird. Yeah, @paulcsmith and I were talking about that earlier. Docker is fine when everything just works, but the second it doesn't it's straight crash and burn lol. Glad you got it working locally though. Once you have something up, be sure to include a screenshot with the PR if you can 😄

**Comment by jwoertink** [comment]
Thanks @robertguss !
