### ISSUE TITLE
Cleaning up docs on updating records

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#194]
I just got bit by this. When looking up how to update records, you'll go to [this guide](https://luckyframework.org/guides/database/validating-saving#updating-records) first. The first part is we mention `params`, but don't really say what `params` looks like (i.e. `Avram::Params.new` vs `Lucky::Params.new`). When writing a spec, I assumed I had to pass in an avram params object as my second argument. In doing that, the record saves, but doesn't actually update. No errors, just no updates. 

Now, we actually do document this [here](https://luckyframework.org/guides/database/validating-saving#saving-without-a-params-object); however, it's a LOT further down the page. I didn't come across it until after a half hour of trying to setup postgres logs locally 😅 

We can easily just add a link below the updating that says "If you need to save without a params object, go here" (or whatever). Also might be helpful to explain what that `params` object is.

**Comment by paulcsmith** [comment]
Yeah I think a note with a link is a good short term situation. In the long term I think it'd make sense to first start with the non-params version and *then* introduce the version with params. What do you think?

**Comment by jwoertink** [comment]
Yeah, that makes sense. Or we can just have a whole section on writing specs and using all this stuff. That way people understand how to write it when writing specs.

**Comment by paulcsmith** [comment]
Can you give an example of a spec? I'm not sure I understand

**Comment by paulcsmith** [comment]
For example, the spec you tried that didn't work and then what you did to fix it.

**Comment by jwoertink** [comment]
Where the first one failed, but the second one passes. I had expected the first one to either work or throw an exception, but it did neither.

```crystal
it "updates thing" do
  thing = ThingBox.create
  Thing::SaveOperation.update!(thing, Avram::Params.new({"field" => "1"}))
  thing.field.should eq "1"
end

it "updates thing" do
  thing = ThingBox.create
  Thing::SaveOperation.update!(thing, field: "1")
  thing.field.should eq "1"
end
```

**Comment by paulcsmith** [comment]
Why did the fist one fail? Was it because the `field` param was not permitted on the operation? If so I would expect it to succeed. But if the param is not permitted it would be nice if we raised a `Avram::NotPermittedError` or something. I think that'd help solve the problem too. What do you think? Is that what you expected?

**Comment by jwoertink** [comment]
Yeah, I didn't actually have a custom `SaveOperation` for this. I just hooked in to the parent class, so I didn't actually permit it. And to be honest, I forgot that was a thing until I just read your comment 😞 I've been in rails land the past few weeks and missing my lucky. 

But yes, when calling `update!` I think it would be ok to raise an exception on that. maybe? I think the main thing was just the docs. Since those two examples are so far apart on the page, I didn't catch it until after.
