### ISSUE TITLE
Document new select_sum! and the return types for select_sum

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website#212]
https://github.com/luckyframework/avram/pull/304

`select_sum!` returns `0` if there are no records to sum. `select_sum` returns `nil`. Integer column types return an Int64. Floats return a Float.

Guide link: https://github.com/luckyframework/website/blob/master/src/actions/guides/database/querying-deleting.cr#L358

**Comment by bdtomlin** [comment]
I'll try to get to this tonight or tomorrow while it's still fresh in my head.

**Comment by paulcsmith** [comment]
That would be wonderful! Thanks @bdtomlin

**Comment by jwoertink** [comment]
Looks like this is already in and deployed. Thanks @bdtomlin!
