### ISSUE TITLE
Change select_tag to select_input in html forms guide

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website#230]
https://gitter.im/luckyframework/Lobby?at=5e635af4afdc1e2033d6540a

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/website/pull/231

**Comment by jwoertink** [comment]
oops 😅  Thanks for fixing that.

**Comment by paulcsmith** [comment]
No prob! I didn't notice it either!
