### ISSUE TITLE
Document `verify_accepted_formats` and `default_format`

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website#251]

**Comment by stephendolan** [comment]
Had some trouble locating the first callout from this issue, but I believe it's this:
https://github.com/luckyframework/lucky/blob/master/src/lucky/verify_accepts_format.cr

The second one is more straightforward, defined here:
https://github.com/luckyframework/lucky/blob/master/src/lucky/request_type_helpers.cr
