### ISSUE TITLE
Better docs on using route helper methods

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#254]
We're not really clear on how you would pass query params using route helper methods. 

https://luckyframework.org/guides/http-and-routing/link-generation
https://luckyframework.org/guides/http-and-routing/routing-and-params#query-parameters

Neither of these pages really show you that you would do `Users::Index.with(page: 1)`. They also don't really tell you that you can do `Guides::Database.path(anchor: "middle-of-page")`.

**Comment by paulcsmith** [comment]
Yeah we should definitely document that :D
