### ISSUE TITLE
Add docs for accessing remote_ip and potential gotchas

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website#255]

**Comment by stephendolan** [comment]
@paulcsmith I'd need a bit more context to tackle this one myself regarding the gotchas you mentioned.

That said, if someone else is comfortable handling this one, here's the file (and doc block) that needs some documentation:
https://github.com/luckyframework/lucky/blob/master/src/lucky/remote_ip_handler.cr

**Comment by jwoertink** [comment]
I think on this one there as a major change in crystal at some point where `remote_address` was a String, but now it's a `Socket::Address` so if you did `request.remote_address == "127.0.0.1"` it would always fail. Also, it's nilable, so you have to do something like `request.remote_address.try(&.address) == "127.0.0.1"`. 

Then the other part to it is that we added this handler to help set that value. In the case of a load balancer, or CDN or something, the original remote_address might be of the LB, so the handler grabs the `X_FORWARDED_FOR` and passes that through. If you set up your own reverse proxy, the header might be `REMOTE_ADDR` or `X-Real-IP` (or a few others that are commonly used). So basically, the user would need to know which header that is and make the changes as necessary)

**Comment by paulcsmith** [comment]
@jwoertink So should we hold off on documenting it until we have better middleware or something?

**Comment by jwoertink** [comment]
I think we can add a simple doc explaining what the handler does to check for the `X_FORWARDED_FOR` header and return the first IP in the value (Separated by comma). Then how to use Crystal's `request.remote_address`. I'm cool with waiting too if you had something in mind for making the handler better.

**Comment by paulcsmith** [comment]
I think that's a good idea to get something in there, even if its not perfect. @stephendolan is this enough to start or do you need more info? I must admit I don't use this method and so can't help much but I can try. or more likely @jwoertink knows and can help!

**Comment by stephendolan** [comment]
As with most of these, I'll dig in and try using it in an app, and summarize what would have helped me get to the end result faster!

Worst case, we'll have a great example of how we _don't_ want to write this up 😬
