### ISSUE TITLE
Update heroku deploy guide to mention seeding required seeds

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#257]
Since we come with a task to seed your DB with required seeds, we should also document how to do this.

Probably just after the Uploading the app section.

https://luckyframework.org/guides/deploying/heroku

**Comment by jwoertink** [comment]
also just noticed that the guides say

> Migrations will happen automatically when the app is pushed to Heroku.

Looking through the [buildpack](https://github.com/luckyframework/heroku-buildpack-crystal) I don't see where that's happening... @paulcsmith do you know where migrations are ran during the heroku deploy? 

If they're not actually being ran, then we should name this section "running tasks" or something, and then document how to migrate and seed and all that.... (or we just update that buildpack to actually do this)

**Comment by paulcsmith** [comment]
@jwoertink They are in the `Procfile` in the release section https://devcenter.heroku.com/articles/release-phase

Maybe we can point to those docs or something to clarify where that happens!

**Comment by jwoertink** [comment]
Ah, heroku magic! Ok, yeah, I think that would be good to note that. You may want to hook in to that, so it would be cool to know how that works.
