### ISSUE TITLE
Remove route inference from the guides and use explicit routes

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website#279]
Part of: https://github.com/luckyframework/lucky/discussions/789#discussioncomment-3296

And also change to not use the parent resource as a module namepsace in routes: https://github.com/luckyframework/lucky/discussions/789#discussioncomment-2855

`Users::Index` not `Projects::Users::Index`

**Comment by jwoertink** [comment]
Context for anyone that lands here looking for an easy task. Any example route that mentions `route` or `nested_route` should just be changed to actual routes.

```
class Users::Index < BrowserAction
  # change this line
  route do
 
  end
end
```

```
class Users::Index < BrowserAction
  # to this line
  get "/users" do

  end
end
```

For example:
https://luckyframework.org/guides/http-and-routing/routing-and-params#automatically-generate-restful-routes
https://luckyframework.org/guides/http-and-routing/routing-and-params#query-parameters
