### ISSUE TITLE
Document custom <link> tags

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#284]
If you use `link()` to try and make `<link>` you're going to have a bad time. You need to use `empty_tag("link", ...)`. We should document this, and also document other custom tags using `tag()`.

**Comment by paulcsmith** [comment]
This is for linking to a stylesheet right? If so I think you'd want to use `css_link` https://github.com/luckyframework/lucky/blob/c333ff1e171eab86c380ab3a7e13e7087c0769d5/src/lucky/tags/specialty_tags.cr#L10

There is also a `js_link` we should document.

**Comment by jwoertink** [comment]
No, if you wanted to set a favicon, you'd use a `<link>` tag, but you wouldn't want it to have a `rel="stylesheet"`. `css_link` might work as a hack if `merge` overrides the existing options (I always forget if that's the case). But you wouldn't go right to `css_link` to make a favicon tag. Same goes for any of the mobile icons like the apple icon, or other `<link>` use cases.

**Comment by paulcsmith** [comment]
What if we add an `icon_link` and `apple_touch_icon_link` that sets the correct `rel` for you and accepts any other args as optional

Then in `link` we can raise at compile if you try to give it just just named tuples. The error would say "try using css_link, icon_link, apple_touch_icon_link`.

Thoughts?

**Comment by jwoertink** [comment]
I think that's fine, but there's a ton of different uses for the `<link>` tag, so making a helper for each one will get very tedious. As long as we've documented how to use `empty_tag` as our escape hatch, then it'll be fine.

If we are going to make some base helper tags, we will want some for these:
`rel="icon"` `rel="apple-touch-icon"` `rel="apple-touch-icon-precomposed"`, `rel="canonical"`

The two apple touch could probably just be an arg passed in. Here's the HTML spec for other link rel types https://html.spec.whatwg.org/#linkTypes

**Comment by paulcsmith** [comment]
@jwoertink Ohhhh wow...didn't realize there were so many options.

That gave me an idea though...what if we let people use `link` with just named args and no block!? Then you use it just like you'd expect

```
link rel: "whatever" src: "anything"

def link(**named_args)
  empty_tag("link", **named_args)
end
```

Either way we should document `empty_tag`, but I think this could be a cool think to add.

I think it'd be fine to do this even though `link` now does either links to other pages, *or* `<link>`, but I thikn it is fine since `<link>` is used pretty infrequently so should be fine...

Toughts?

**Comment by jwoertink** [comment]
Wait, so you're saying allow this? 🤔 

```crystal
# <link rel="icon" href="/favicon" />
link rel: "icon", href: "/favicon.ico"
# <a rel="shortcut" href="/favicon">Icon</a>
link "Icon", rel: "shortcut", to: Favicon::Show
```

**Comment by paulcsmith** [comment]
@jwoertink Yes for the first thing, I had no idea that second thing is valid HTML... is it?

But also I think that second example should already work?

**Comment by jwoertink** [comment]
Yes, and yes. Adding `rel` attributes to anchor tags is valid, and common, and it does work currently.

Do you think it would be confusing to have the same method name generate 2 different HTML tags depending on what you pass in? I guess there's almost never a case those two would be near each other since `<link>` goes in the `<head>` which is almost always in a separate component... So maybe the context switching won't be bad? We could always give it a shot. Or maybe open a discussion to see what others think about naming?

**Comment by paulcsmith** [comment]
Yeah I think it would be ok as long as we document it

* If passed a block or String, and an action to link to, it will generate an `a`
* Otherwise it will create an empty `link` tag

I think we can give it a shot and see! This seems like on of those things that is hard to tell without actually shipping it and trying it out. Thoughts?

**Comment by jwoertink** [comment]
Yeah, I agree. You really need to just try it out to see. I'm cool with that.

**Comment by jwoertink** [comment]
I'm gonna close this because we already have some [docs](https://luckyframework.org/guides/frontend/rendering-html#special-tags-link-form-helpers-etc) pointed to doing custom `<link>` tags, and [several examples](https://luckyframework.org/guides/frontend/rendering-html#perma-empty-tag).
