### ISSUE TITLE
Alternate ORM guide recommends deprecated API

### ISSUE THREAD

**Issue by z64** [luckyframework/website#302]
The [Alternate ORM](https://luckyframework.org/guides/database/intro-to-avram-and-orms#alternate-orms) guide instructs the following snippet:

```cr
# config/database.cr
Avram::Database.configure do |settings|
  settings.url = "unused"
end

MyOtherAdapter.configure do |settings|
  settings.url = "my_other_adapter_url"
end
```

`Avram::Database.configure` appears to be deprecated in favor of `Avram.configure` (or `AppDatabase.configure`)?:

- [Avram::Database.configure source](https://github.com/luckyframework/avram/blob/master/src/avram/database.cr#L13-L24) is a macro error
- [Lucky CLI skeleton](https://github.com/luckyframework/lucky_cli/blob/5aabbae7e60627451cf71fe60b88c908be61802a/src/web_app_skeleton/config/database.cr.ecr#L19) furnishes `AppDatabase.configure`, which appears to be the successor of the guide's original snippet

EDIT: I see now it's supposed to be invoked on a subclass of `Avram::Database`. So that's probably what should be conveyed in the guide?

**Comment by jwoertink** [comment]
Ah, good catch. Yeah, this is a common pattern I've used:

```
class NoDB < Avram::Database
end

NoDB.configure do |settings|
  settings.url = Avram::PostgresURL.build(
    hostname: "localhost",
    database: "unknown",
    username: "none"
  )
end
```

But it could just be `settings.url = "unused"`. We just need to update the guide on that.
