### ISSUE TITLE
Add a CookBook section

### ISSUE THREAD

**Issue by wout** [luckyframework/website#313]
I've been thinking about this for a while now and adding a CookBook/Micro Tutorial section makes sense. The Guides are already very elaborate, but it would help users to show them how to use Lucky with features that are too specific, opinionated or beyond the scope of the Guides, although still Lucky-specific.

I think we all have great solutions lying around that would help users jump-start their projects. For example, I created a [Mailjet](https://github.com/tilishop/mailjet.cr)-powered newsletter subscription form with a few spam-bot traps. Or a flexible, well-structured [I18n.cr](https://github.com/vladfaust/i18n.cr) implementation that uses the current class name + namespace for its nested keys, so you don't have to think about structuring your locale files. But there are also shards like @confact's [`lucky_can`](https://github.com/confact/lucky_can) or my [`lucky_svg_sprite`](https://github.com/tilishop/lucky_svg_sprite.cr). 

Those things don't belong in the Guides, but would still be very valuable to have. They could be posted on DEV.to or Medium, but they would disappear in the noise quickly. Better even, they could have a place on those platforms and in the site somewhere as well.

It's true that it adds maintenance, but that's easily solved. We can have an app containing all those implementations which can be run through Travis or Github Actions at every release, just to see if everything is still functioning correctly.

Food for thought. :blush:

**Comment by paulcsmith** [comment]
....you read my mind haha. Or I read yours! I just posted this in Gitter:

> The current plan that I have not documented is to change "Guides" -> "Learn" which takes you to a page with:
>
> - Guides
> - Screencasts
> - API Reference
> - Cookbook

So yeah, I like this idea :)

**Comment by wout** [comment]
Freaky, I just saw it too. 🤯️ 😂️

**Comment by jwoertink** [comment]
I actually had the same thought recently. What if we had a "Community Guides" section? We could actually do a whole "awesome-lucky" section. There's already a repo for that, but I don't know how well it's updated. By having this list right on our website, we can showcase the community effort to add shards. This would also let us do tutorials by those authors right in those sections.

**Comment by jwoertink** [comment]
oh man, @paulcsmith right on top of it. 😂

**Comment by wout** [comment]
I'd like to help with that. We've been building our own product page (will be released soon) by the example of the Lucky website, so I know its structure very well.

On a side note, I love how you guys built it. It's like having Jekyll without the downsides of being static.
