### ISSUE TITLE
Document file uploads

### ISSUE THREAD

**Issue by wout** [luckyframework/website#330]
As described in https://github.com/luckyframework/lucky/issues/1194.

**Comment by matthewmcgarvey** [comment]
Here's the basics of how to do it.

On a SaveOperation add `file_attribute :image`, then in the html form add `multipart: true` to the `form_for` and then add `mount Shared::Field, op.image, &.file_input` within the form. Pass the `params` object into `SaveOperation.create`. In a `before_save` use the `image` to save or upload. Maybe using the https://github.com/jetrockets/shrine.cr shard.

So here is an example using Shrine...
```crystal
class SaveUser < User::SaveOperation
  permit_columns name
  file_attribute :profile_picture

  before_save do
    profile_picture.value.try { |pic| upload_pic(pic) } 
  end

  private def upload_pic(pic)
    result = Shrine.upload(File.read(pic.tempfile.path), "store", metadata: { "filename" => pic.filename })
    profile_picture_path.value = result.url
  end
end
```

```crystal
class Users::Create < BrowserAction
  post "/users" do
    SaveUser.create(params) do |op, user|
      if user
        redirect to: Users::Show.with(user.id)
      else
        html Users::NewPage, op: op
      end
    end
  end
end
```

```crystal
class Users::NewPage < MainLayout
  needs op : SaveUser

  def content
    form_for Users::Create, multipart: true do
      mount Shared::Field, op.name
      mount Shared::Field, op.profile_picture, &.file_input
    end
  end
end
```

Obviously the explanation isn't that great but the code examples should help whoever picks this up 😄

**Comment by paulcsmith** [comment]
This is super awesome. Thanks @matthewmcgarvey 

Pretty straightfoward and the examples are super helpful!
