### ISSUE TITLE
Para adds `,` and breaks stuff

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website#360]
Para adds a `,` and results in invalid Crystal

```html
<p class="wut">
Text
</p>
```

Results in

```crystal
para, class: "wut" do
  text " Text "
end
```

**Comment by jwoertink** [comment]
I just tried several examples, and it looks like this may have been fixed at some point. 
<img width="1061" alt="Screen Shot 2020-07-08 at 3 57 27 PM" src="https://user-images.githubusercontent.com/2391/86978416-bdcc5800-c133-11ea-9dbe-73a1cf9a8844.png">

I'll close this out for now.
