### ISSUE TITLE
Document current_page

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website#371]
https://github.com/luckyframework/lucky/blob/255e1f429efac336741020a3d9e8554f741f2baf/src/lucky/page_helpers/url_helpers.cr

**Comment by stephendolan** [comment]
@paulcsmith / @jwoertink 

Where do y'all think this should go? Perhaps a new major section in https://luckyframework.org/guides/http-and-routing/routing-and-params? It also might make sense in https://luckyframework.org/guides/http-and-routing/link-generation.

**Comment by jwoertink** [comment]
My thought was it could go here https://luckyframework.org/guides/frontend/rendering-html#page-helpers 
It is used with routing stuff, but it's a helper method you use in your pages and components like these.

**Comment by paulcsmith** [comment]
Yeah I think in page helpers as well 👍

**Comment by stephendolan** [comment]
It shall be done!
