### ISSUE TITLE
Add "Copy" button for HTML converter

### ISSUE THREAD

**Issue by stephendolan** [luckyframework/website#386]
It'd be really nifty to be able to click a button to copy your converted code from https://luckyframework.org/html!

I just implemented that this evening in a Lucky app, but I used StimulusJS to make things less gross. What are the core team's thoughts on introducing Stimulus to this project to provide some JS sprinkles?

**Comment by paulcsmith** [comment]
Great idea! I think if we can use regular old HTML that'd be preferable for now. We don't really do much with JS so keeping it as simple as possible would be good.

Also because eventually this website will be the test bed for Fusion 😉

**Comment by stephendolan** [comment]
Oooooh! Okay, I'll tinker a bit and see what I can come up with that doesn't use Stimulus.
