### ISSUE TITLE
Add a "Built with Lucky" page / section on the website

### ISSUE THREAD

**Issue by konung** [luckyframework/website#414]
> Because bragging rights!

Hi.
I really like Lucky, and the fact that luckyframwork.org is dogfooding is awesome!  

I introduced several colleagues/peers to Lucky and Crystal and while they like the idea they are hesitant to give it a try.  Because "enterprise people" want some kind of "social proof" that this tech stack "works".  It's just a reality of how tech stacks get adopted in larger companies. 

I think it would be beneficial from the marketing / "spreading the word" perspective, to have a "built with lucky" section. One of the main criteria I find myself using when evaluating a language / framework, beyond a casual interest/toy, is to see what's possible to build with it. And especially what other folks built with it. 

For example, one of the biggest selling points of Rails (aside from productivity + developer happiness + size of community), despite some people persisting that Ruby is slow, is the fact that so many big websites/companies have used RoR successfully - Twitter, Shopify, Airbnb, Bloomberg, GitHub, etc. 

Another example: the thing that put Phoenix/Elixir on the map, at least for bigger companies, was the fact that  BleachReport, Pinterest, and most recently PepsiCo came out saying that they built big parts of their infrastructure with it. 

I've heard the Lucky's Core Team on podcasts mention that they built large projects with Lucky (with millions of users). But it would be really interesting if they mentioned a few "case-studies", even as blog-posts or just simple small "testimonials" 

> We built the NextBigApp using Lucky in 20 minutes. It can handle 500 gazillion users on a single $5 cloud droplet, and we only used 1.5 DevOps engineer to do it. 

As they say "A picture is worth a 1000 words". In this case, a few links to existing projects could increase interest in Lucky. Especially if it's in the form of a short podcast or a blog post. :) 

## Summary
1. Have a list of "built with lucky" websites
2. Add several write ups / blog posts about how Lucky improved an existing project, or possibly made it possible to build a big project with minimum resources from scratch. Examples of the posts I'm referring to:
  a. https://moz.com/devblog/moz-analytics-db-free
  b. https://blog.discord.com/scaling-elixir-f9b8e1e7c29b

**Comment by jwoertink** [comment]
I totally agree. This also goes along with https://github.com/luckyframework/website/issues/313 in which we wanted a section of the site that can showcase projects / shard enhancements / whatever else the community has (i.e. lucky diff, lucky casts, etc...). I'm sure this is something we will do and most likely post 1.0 (which isn't too far off). A lot of companies like the ones you mentioned also prefer to wait for that magic number too. But once Crystal and Lucky are 1.0, we should see a decent adoption. 

Thanks for the support!
