### ISSUE TITLE
Review GitHub Action

### ISSUE THREAD

**Issue by stephendolan** [luckyframework/website#430]
One of our community members in Discord noted [here](https://discord.com/channels/743896265057632256/743896265057632259/757528732532604970):
>  luckyframework/website CI config uses cache wrong, it setup it after node and shards install, and tries to cache "crystal spec" result only

The same user posted this example later as what they ended up with, presumably one that's more "correct":
> Here is my version of GitHub action CI for lucky https://github.com/skojin/lucky-bug-honeypot/actions/runs/265793967/workflow

I haven't verified this personally, but wanted to submit in case there really is a chance to optimize our Actions.

**Comment by matthewmcgarvey** [comment]
This might already be done? https://github.com/luckyframework/website/pull/425

**Comment by stephendolan** [comment]
Oh nice! Yes, definitely closed by #425.
