### ISSUE TITLE
Document Lucky Flow's `take_screenshot` method

### ISSUE THREAD

**Issue by stephendolan** [luckyframework/website#431]
Perhaps we could add a little "Debugging" section to https://luckyframework.org/guides/testing, or just insert a new sub-item in https://luckyframework.org/guides/testing/html-and-interactivity.

It'd be nice to have something pop up in the guides when I searched "Screenshot". I ended up having to dig into the Lucky Flow source to find the method, but it's been really handy! Here's that definition: https://github.com/luckyframework/lucky_flow/blob/master/src/lucky_flow.cr#L48

**Comment by jwoertink** [comment]
Related: https://github.com/luckyframework/website/issues/199
