### ISSUE TITLE
Document GitHub Actions CI/CD Options for Lucky Applications

### ISSUE THREAD

**Issue by stephendolan** [luckyframework/website#439]
See:
https://github.com/luckyframework/lucky/issues/1077 for some historical context
https://github.com/luckyframework/website/pull/283 for an (older) pull request that already defined some of the content we could use

This section should probably feel similar to the "Deployment" section, where it's essentially a how-to guide for getting CI/CD up and running quickly.

I'd recommend that the initial PR for this only includes GitHub actions since it's what the team and community seems to have the most experience with resolving at this point in time. We can then open up sequential PRs as needed for things like:
- CircleCI
- GitLab CI
- Travis

**Comment by paulcsmith** [comment]
Note that we are likely going to generate a GH Actions file so this could be a pretty simple overview of the generated file, and maybe later some tips on customization https://github.com/luckyframework/lucky_cli/pull/559
