### ISSUE TITLE
Add a sitemap

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#442]
We should have a sitemap at `/sitemap.xml`. 

https://github.com/jwoertink/sitemapper 😬

**Comment by stephendolan** [comment]
@jwoertink Do you have any advice on adding this to a Lucky application specifically?

From reading the Usage section on your repo it feels like something that could even be a Lucky custom task that's run in a GitHub Action... but is there another simpler way that I'm not thinking of?

**Comment by jwoertink** [comment]
Sitemapper would go in a task for sure since it's not required to run the application. For this website, I don't think we'd have to generate a new sitemap through a cron job or anything. What would be nice is if it happened during deployment. I don't know how that would look, or what Heroku would allow, but to make it easy, we could just run that manually when we know we need to deploy. 

We would just run `lucky gen.sitemap` and send up a PR saying it was updated. Then we just deploy like normal. 

As for what the task does, we can hook in to the [guides](https://github.com/luckyframework/website/blob/master/src/models/guides_list.cr) to display all those, and maybe [for the blog too?](https://github.com/luckyframework/website/blob/master/src/posts/base_post.cr) and have it auto generate all the pages for us.

**Comment by matthewmcgarvey** [comment]
That's funny, because it literally is the example for custom lucky tasks https://luckyframework.org/guides/command-line-tasks/custom-tasks

**Comment by jwoertink** [comment]
I wonder who wrote that? 😬

**Comment by stephendolan** [comment]
Cool, that's really helpful!

Thoughts on tagging releases of the website? It'd allow us an easy hook in GitHub actions for when to run the task and commit the new code automatically. Idk how we'd number the releases or anything, but it seems like a good trade-off to have to tag a release rather than remembering to run the sitemap task and submit a PR.

In thinking of that, I guess we could also use a new release tag to deploy new site content, which might be handy!

**Comment by jwoertink** [comment]
I'm open to whatever is easy doesn't require much thought from me because I'll forget either way 😅

**Comment by stephendolan** [comment]
Cool! I think if we could eliminate manual deploys and just rely on tags to auto-deploy, that'd be the best of both worlds to do any pre-release stuff *and* make it easier to tell when the site's been updated.

I'll probably try to tackle this next week.
