### ISSUE TITLE
Review Algolia Configuration

### ISSUE THREAD

**Issue by stephendolan** [luckyframework/website#443]
This is mainly a list of items we may want to consider to make the Algolia stuff on the Lucky website a bit easier to understand and maintain.

- [x] Correct this `.com` to `.org`: https://github.com/algolia/docsearch-configs/blob/master/configs/luckyframework.json#L7
- [x] Correct this sitemap once #442 is resolved: https://github.com/algolia/docsearch-configs/blob/master/configs/luckyframework.json#L7 
- [ ] Open a PR to add a comment around the Algolia stuff in this repository's codebase so that it doesn't all live in Paul's head :). Including a link to DocSearch and the Algolia open source page might be helpful!
- [ ] Migrate to new Algolia setup.
- [ ] Add Algolia crawler to github actions

**Comment by jwoertink** [comment]
I've opened the PR to first item 1 https://github.com/algolia/docsearch-configs/pull/4055

**Comment by jwoertink** [comment]
https://github.com/marketplace/actions/algolia-crawler-automatic-crawl
https://docsearch.algolia.com/docs/migrating-from-legacy/

I have a new appId, and apikey for the new setup all in an email. The migration must be done before March 2022.
