### ISSUE TITLE
Suggest installing heroku or other process manager over overmind if using WSL

### ISSUE THREAD

**Issue by Jigsik** [luckyframework/website#469]
Overmind has a known issue which might occur when using WSL (Windows Subsystem of Linux).

This is what I got when running "lucky dev" or "overmind start":
**listen unix ./.overmind.sock: bind: invalid argument**

It caused me some headache and I end up removing overmind and installing heroku-cli instead.

I think it would be great to mention this in the documentation :-). I can do that if there is no reason to do that at all.

Thanks for response!

**Comment by jwoertink** [comment]
Hey! Thanks for the suggestion. Are you using WSL 1 or WSL2? I wonder if that makes a difference 🤔 or is it still an issue on both?

**Comment by jwoertink** [comment]
Related: https://github.com/DarthSim/overmind/issues/88

**Comment by mdwagner** [comment]
Just wanted to mention that I've been using [Hivemind](https://github.com/DarthSim/hivemind) on WSL for over a year with no issues.

**Comment by jwoertink** [comment]
Thanks for the heads up @mdwagner. That'll be good to point people to.
