### ISSUE TITLE
Document association options

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#483]
The model association methods like `belongs_to` have options like `foreign_key`, or `table` that should be documented. 

https://github.com/luckyframework/avram/blob/master/src/avram/associations/belongs_to.cr#L2
https://luckyframework.org/guides/database/models#belongs-to

**Comment by matthewmcgarvey** [comment]
I guess I can include here that has_many through updates need to be documented.

`table` was also removed from `belongs_to` associations

**Comment by jwoertink** [comment]
Yeah, now that we have those updates, we will have to change what needs to be documented. It also had to wait for next release now.
