### ISSUE TITLE
Add keyboard shortcut to focus search 🙏

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/website#490]
I'd love it if `/` would focus the search input!

**Comment by stephendolan** [comment]
@matthewmcgarvey Agreed that this would be fantastic. I've spent some time digging in recently, actually.

Here's an issue on their repo discussing:
https://github.com/algolia/docsearch/issues/973

It **seems** like we'll have this in the next version (3.0), at which point we can bump the include in `layout_head.cr` and have it available.

I briefly looked into bumping us to the v3.0.0 alpha to test, but it seems as though the jsdeliver and unpkg links don't have minified dist files yet.

**Comment by jwoertink** [comment]
Just to make it easier to check back, it looks like we're just waiting on this to be available

https://cdn.jsdelivr.net/npm/docsearch.js@3/dist/cdn/docsearch.min.js

**Comment by jwoertink** [comment]
not sure if this just changed or not, but I just hit `tab` and it focuses the search...

**Comment by matthewmcgarvey** [comment]
I hope that algolia didn't take over tab. I thought that was an accessibility feature to cycle through available targets

**Comment by stephendolan** [comment]
Yeah, Tab isn't doing anything for me except the standard browser tabbing from the homepage!
