### ISSUE TITLE
Soft Delete documentation on setting default conditions no longer works

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/website#497]
With the update to Avram to clone the query on every method call, putting conditions in the `#initialize` method no longer works. Generally, I believe we don't have any documentation on how to implement "default scoping" (setting conditions on the query by default) with Avram, which is what these docs were explaining.

To fix this in my project (though not soft delete related) I updated the code to...
<img width="384" alt="CleanShot 2020-11-25 at 18 45 50@2x" src="https://user-images.githubusercontent.com/17329408/100295327-f50a9c80-2f4e-11eb-89f0-3f0e5aabcf29.png">

**Comment by jwoertink** [comment]
oh yikes... You can't set default queries in the initialize anymore? That's actually used quite a bit by people I thought. I know I have a few spots in my projects. I must not be on the latest stuff. We definitely need to fix that. I'll open an issue on avram about that.
