### ISSUE TITLE
Markd doesn't support tables

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#50]
I was hoping to do something like this in the guides

```
| Task | Description |
|------|-------------|
| db.x  | whatever   |
```

But turns out the markdown parser being used doesn't support tables https://github.com/icyleaf/markd/issues/4

I'm not sure if the built in one does or not https://crystal-lang.org/api/0.29.0/Markdown.html I'm not sure what the differences between those two are.

**Comment by paulcsmith** [comment]
The built in one has even worse support for almost everything :P I started using it and had tons of issues.

I think for now we’d either need to add support to Markd or use HTML. I believe you can use whatever HTML you want and markdown will render it as-is

**Comment by watzon** [comment]
Yeah I've played with the built in parser's source code, it's kind of a mess and definitely nowhere near the common mark spec. I imagine tables would be one of the harder things to add though, so I'm not surprised it hasn't been implemented in markd.

**Comment by paulcsmith** [comment]
I'm gonna go ahead and close this since I think this is a Markd issue not a website issue
