### ISSUE TITLE
Enum permalink is wrong

### ISSUE THREAD

**Issue by robacarp** [luckyframework/website#504]
The link to the Enum section [in the Column-Types](https://luckyframework.org/guides/database/models#column-types) (find on page "see using enum") section points to a permalink "#perma-using-enum", but the actual section id is just "#using-enums"

Similarly, https://luckyframework.org/guides/database/validating-saving#perma-saving-enums and https://luckyframework.org/guides/database/querying-records#perma-querying-enums both from https://luckyframework.org/guides/database/models#using-enums (find on page "To learn more about using enums")

**Comment by jwoertink** [comment]
Strange... I'd need to dig in more, but that's setup here https://github.com/luckyframework/website/blob/master/src/actions/guides/database/models.cr#L251 The anchors don't go to the title, but instead to specific anchors added in the code... Did this break recently? I noticed in the markup there's now a `<!-- raw HTML omitted -->` 🤔

**Comment by stephendolan** [comment]
@jwoertink I don't see anything in the Dependabot updates that would have affected this:
https://github.com/luckyframework/website/pulls?q=is%3Apr+is%3Aclosed+label%3Adependencies+

Do you think this has been broken for a while? I remember that we changed out the markdown rendering library _somewhat_ recently, and I can confirm that when I manually test things on the website anchor links weren't really on my radar.

**Comment by jwoertink** [comment]
That might be the case. The [permalink](https://github.com/luckyframework/website/blob/master/src/actions/guide_action.cr#L22-L24) method just takes the ID and creates a `div` with that id set. I bet the new rendering library would need that to be escaped somehow 🤔  I guess that was one thing I missed when I moved over to the new lib

**Comment by jwoertink** [comment]
This is fixed now! Thanks for catching that @robacarp
