### ISSUE TITLE
Where is this serviceworker deal coming from?

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#521]
Just started noticing this after the latest updates. I'm assuming some related to a yarn package that updated, but need some investigating.

```
web          | GET /serviceworker.js
web          |  ▸  Lucky::RouteNotFoundError
web          |
web          |      Could not find route matching GET /serviceworker.js
web          |
web          |     Backtrace
web          |
```

**Comment by stephendolan** [comment]
Interesting... I'll dig in when I upgrade some apps this weekend. That feels like a Progressive Web App (PWA) thing.

**Comment by stephendolan** [comment]
@jwoertink I'm having trouble reproducing this on my end, is this something you're seeing in a newly-generated app, or an existing one that you upgraded?

If it's an existing one, could you provide your Package.json and `webpack.mix.js` contents?

**Comment by jwoertink** [comment]
It's coming from this app... The website itself. While I was working on some docs I saw it popping up in my `lucky dev`

**Comment by jwoertink** [comment]
After upgrading the site to laravel-mix 6, and all the latest stuff, I no longer see this. Checked all the different browsers. Must be good now.
