### ISSUE TITLE
Code example error in 0.25 announcement post for has_many through:

### ISSUE THREAD

**Issue by rmarronnier** [luckyframework/website#541]
```crystal
# Before update
class User < BaseModel
  table do
    has_many posts : Post

    # you specified the Symbol of the has_many method to query through
    has_many comments : Comment, through: :posts
  end
end

# After update
class User < BaseModel
  table do
    has_many posts : Post

    # you specify an Array(Symbol) where the first item is the method to query through
    # and the second item is that association's method.
    has_many comments : Comment, through: [:posts, :comments]
  end
end
```
should be
```crystal
# Before update
class User < BaseModel
  table do
    has_many posts : Post

    # you specified the Symbol of the has_many method to query through
    has_many comments : Comment, through: :posts
  end
end

# After update
class User < BaseModel
  table do
    has_many posts : Post

    # you specify an Array(Symbol) where the first item is the method to query through
    # and the second item is that association's method.
    has_many comments : Comment, through: [:posts, :comment]
  end
end
```
Notice the singular form in `has_many comments : Comment, through: [:posts, :comment]`
The guide section is correct though :-D

**Comment by matthewmcgarvey** [comment]
@rmarronnier The through array items match the association names. So the way the associations are named means that `Post` should have `has_many comments : Comment` defined. With your change, it would most likely have a `belongs_to comment : Comment` defined. Neither are right or wrong.  Does that make sense or am I missing something?

**Comment by rmarronnier** [comment]
Ok, that makes sense. I posted this because I used a `belongs_to` type of relation to indirectly bind the two models like in the avram spec testing Post and Tag and got errors when using a plural form when calling `post.preload_tags` etc.
Sorry for the noise and thanks for the explanation.

**Comment by jwoertink** [comment]
Ah, good catch @rmarronnier! Yeah, I guess I was thinking a post has_many comments in this case like @matthewmcgarvey was saying. The nice thing is with this new update, you gain so much more flexibility! 🥳
