### ISSUE TITLE
Simplify the guide routing with glob routes

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/website#544]
Instead of having an action for every guide, we could possibly use glob routing.

There could be a `Guides::Show` action with a path of `/guides/*:guide_path` and that `guide_path` could point at the markdown content. If there's no markdown content connected to it, we'd return a 404 so that there would be no differences in behavior.

I think this might also be an opportunity to move the markdown into actual markdown files.

**Comment by jwoertink** [comment]
The different actions allows us to link to different guides using the action routing in sort of a type-safe way to protect us from removing a guide without updating all of the links. If we moved them in to markdown files, we'd have to run them through an ECR preprocessor for things like the `permalink()` for the page anchors and such.
