### ISSUE TITLE
Update JSON Request docs

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/website#553]
The [parsing JSON request docs](https://luckyframework.org/guides/json-and-apis/parsing-json-requests) are basically empty. They don't contain any Lucky-specific information like how to access the json data. It should probably be combined with the doc on [saving JSON to the database](https://luckyframework.org/guides/json-and-apis/saving-to-the-database) as a two part documentation on how to handle JSON requests. The [CORS docs](https://luckyframework.org/guides/json-and-apis/cors) could probably be thrown in as well.

**Comment by jwoertink** [comment]
This was technically resolved by https://github.com/luckyframework/website/pull/632 We can continue to add more to it, but I believe this original issue was because that page used to be almost blank 😅
