### ISSUE TITLE
Guides say select_count returns Float64... it doesn't

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#592]
The guides for the `select_count` method [here](https://luckyframework.org/guides/database/querying-records#select-count) say that it returns `Float64`, but it actually returns `Int64` as shown [here](https://github.com/luckyframework/avram/blob/master/src/avram/queryable.cr#L201)

**Comment by nodeMD** [comment]
Hello 😃 
I've created a small PR to address that issue: https://github.com/luckyframework/website/pull/649
Please take a look and review when you will have a moment 🙂
