### ISSUE TITLE
Found a few typos on the pagination guides

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#600]
This part says `IndexPages` (plural) https://luckyframework.org/guides/database/pagination#paginating
This part also says `IndexPages` instead of `IndexPage` https://luckyframework.org/guides/database/pagination#paginate-arrays

This part is a page, but shows defining a `render` method instead of the `content` method https://luckyframework.org/guides/database/pagination#html-components

This section references the old `m` method in `m PaginationLinks`, but should be `mount` https://luckyframework.org/guides/database/pagination#customizing-built-in-components

**Comment by 96RadhikaJadhav** [comment]
@jwoertink  Can I work on the issue?

**Comment by jwoertink** [comment]
@96RadhikaJadhav sure! Have at it 🎉  Thanks 😄

**Comment by matthewmcgarvey** [comment]
Closed by https://github.com/luckyframework/website/pull/601
