### ISSUE TITLE
Figure out how to reliably render multi columns in the guides table of contents

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website#62]
https://twitter.com/staleo/status/1139202758219902976

Maybe we do this in Crystal instead. Split it into 2 rows if over a certain size

**Comment by jwoertink** [comment]
I'm not sure if this is still an issue or not. I've checked Safari, Brave, Chrome, Edge, Firefox, and on macOS, and Arch Linux. I've asked Staleo if it's still an issue on Twitter to hopefully confirm, but my guess is this is fine now.

**Comment by jwoertink** [comment]
Looks like we're all good now! https://twitter.com/staleo/status/1236322456350097408?s=21
