### ISSUE TITLE
Address duplicate search results

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/website#637]
The search results are powered by our markdown headings. Sometimes we have multiple headings with the same words which makes duplicate search results.

Could we go through and either remove duplicate headings we don't need or make them more specific?

Example:
<img width="482" alt="CleanShot 2021-04-18 at 15 40 03@2x" src="https://user-images.githubusercontent.com/17329408/115158529-96a89c80-a05c-11eb-9d56-d4bde045de22.png">

**Comment by jwoertink** [comment]
This was fixed with the Algolia update:
![Screenshot from 2022-06-03 16-09-39](https://user-images.githubusercontent.com/2391/171965408-beb8fa41-1974-4294-9705-fa0bc3d21588.png)
