### ISSUE TITLE
Add a /chat action to redirect to discord

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#680]
Trying to remember the discord link is hard, and it takes "30 boosts" to enable vanity URLs for discord. Instead, we can just make an action `/chat` that just redirects to the Discord link.

**Comment by stephendolan** [comment]
I just use https://short.io/ for LuckyCasts.

If you've got access to the luckyframework.org DNS, we could do something like:
- https://link.luckyframework.org/chat
- https://link.luckyframework.org/discord

Then we have an avenue for easy-to-remember links for other stuff in the future (Twitter, GitHub, etc) as well

**Comment by jwoertink** [comment]
I don't have access to that. Maybe @paulcsmith can hook us up!
