### ISSUE TITLE
The step `db.create` is missing in the tutorial

### ISSUE THREAD

**Issue by haarts** [luckyframework/website#699]
When following the tutorial at one point you create a new resource: https://luckyframework.org/guides/tutorial/new-resource

Running the migration fails with an opaque "unable to connect" error. This is because the database has not been created yet. That step is missing. `lucky db.create`. After that everything works fine. (Bonus points for making the error message more clear.)

**Comment by jwoertink** [comment]
That step is actually ran from the `./script/setup` https://luckyframework.org/guides/tutorial/overview#setup-script When you run that script, it will run `lucky db.create` for you https://github.com/luckyframework/lucky_cli/blob/d9aa95c2fd3d2b3d41c012233c8d3236ca72c6d9/src/web_app_skeleton/script/setup.ecr#L34

So I guess my question is, was this a step you missed? Or did you run that step, and something else went wrong? 🤔

**Comment by haarts** [comment]
Surely that's a step I've missed. My apologies. I've been going back and forth in that doc. Closing! Thanks for the reply and clarification.

**Comment by jwoertink** [comment]
Ah ok. I'm sure we can work out making the tutorial steps a bit easier to follow. Not quite sure how, yet, but I'm glad it's working out.
