### ISSUE TITLE
Guide: "Database -> Validating, Saving, and Deleting" section contains no information about deleting a record

### ISSUE THREAD

**Issue by taylorthurlow** [luckyframework/website#70]
Here's the section in question: https://luckyframework.org/guides/database/validating-saving-deleting

It contains nothing about deleting a record despite the section name suggesting that it does.

**Comment by paulcsmith** [comment]
@jwoertink maybe this was accidentally omitted in the new guide rewrite? If you want to work in this can you assign yourself? If not I’ll try to tackle it tomorrow!

Thanks for opening @taylorthurlow! In the meantime, to delete a record you find it with a query and call “delete” on it

**Comment by taylorthurlow** [comment]
I was able to find it in the generator template, so no problem!

**Comment by paulcsmith** [comment]
Looks like I deleted it and forgot to move it over. Oops! https://github.com/luckyframework/website-v2/commit/f5760bb4520e16d17f8cc4f34ae7db3c2946fee4#diff-3998ef0b82c26e4e56e3829ca2fa6043L191

😆

**Comment by jwoertink** [comment]
I added some docs about doing deletes in one of them. The thing though is that the validating, etc.. page is about using Forms (SaveOperation) which doesn't handle deletes. I gotta look how I wrote that out, but I know it's in there.
