### ISSUE TITLE
Host brand/media assets

### ISSUE THREAD

**Issue by stephendolan** [luckyframework/website#705]
We should make it as easy as possible for folks to spread the word about Lucky, including using our logo and color schemes!

I'm thinking of something very similar to what Crystal itself has done here:
https://crystal-lang.org/media/

**Comment by jwoertink** [comment]
This is done now, right? https://github.com/luckyframework/website/pull/712

**Comment by stephendolan** [comment]
Oh yeah! Sorry, forgot about this issue.
