### ISSUE TITLE
My PRs no longer deploy

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#735]
I'm not sure how this is setup... maybe @paulcsmith knows something here... When I make a PR, it will auto deploy to heroku. The setup for this still uses the old crystal buildpack which doesn't work with Lucky anymore. I can log in to heroku and manually update this, but I'd like to get it setup so they "just work" again.

**Comment by matthewmcgarvey** [comment]
Closed with https://github.com/luckyframework/website/pull/934
