### ISSUE TITLE
Better flow setup guides

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#766]
I just setup a fresh machine on Linux, and I didn't see anything that told me to install chrome. I ran my app's flow specs, and they blow up because I didn't have chrome installed. 

https://luckyframework.org/guides/getting-started/installing

this page should also mention that if you want to use Flow, you'll need to install Chrome, and maybe that Flow is supposed to auto install the chromedriver stuff for you.

**Comment by ghost** [comment]
@jwoertink I'd like to work on this 😆 As I also ran into this on my arch machine 😉. I assume that a 6 day old issue is still relevant 😆. Not like issues from 2018 😉

**Comment by jwoertink** [comment]
hahah! Yes, very relevant. Have at it! I think the getting started installation section should just mention what you will need to install. Notice at the bottom of that page where it says you need node and yarn (optional), but it doesn't say how to install, just links off. Then it can also link over to the section about Flow itself https://luckyframework.org/guides/testing/html-and-interactivity
