### ISSUE TITLE
Add generic deployment guide

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website#80]

**Comment by mwlang** [comment]
How generic do you you want this to be?

Should I only cover components of the system that must be installed?  i.e. Crystal, yarn, etc. 

Or, should I say, write instructions and commands to issue to install a complete system onto Ubuntu 18.04 and MacOS that can likely be interpolated to other system installs?

**Comment by paulcsmith** [comment]
I think at first just what components to instal and what commands to run. Then later what commands to install

But if you have them ready please share a full install on Ubuntu as we may use that in the future!

**Comment by edwardloveall** [comment]
Yeah, honestly we need _any_ start we can get. If you have very specific Ubuntu instructions, those are way more helpful than nothing. Same goes for generic instructions or anywhere in between.

**Comment by jwoertink** [comment]
This has been added in with https://github.com/luckyframework/website/pull/81
