### ISSUE TITLE
mention i18n

### ISSUE THREAD

**Issue by testbird** [luckyframework/website#83]
The docs could provide some info about internationalization support.
Maybe with the help of https://github.com/vladfaust/i18n.cr ?

**Comment by jwoertink** [comment]
Lucky doesn't support i18n yet https://github.com/luckyframework/lucky/issues/631

**Comment by testbird** [comment]
Maybe mention such desired things in a roadmap or todo, with a hint where/how someone could fit it in.

I don't know, but maybe something like "Providing helper for integrating one of the i18n libs in BrowserAction?
https://github.com/vladfaust/i18n.cr
https://github.com/whity/crystal-i18n

**Comment by jwoertink** [comment]
We actually have this documented now https://www.luckyframework.org/guides/frontend/internationalization
