### ISSUE TITLE
mention file/media uploads

### ISSUE THREAD

**Issue by testbird** [luckyframework/website#84]
The docs could provide some info about file uploads.

(Ideally providing a versioned download filename, and a default path that always redirects to latest replacement version.)

**Comment by rnice01** [comment]
It looks like the Amber docs has an example on how to upload an image. Would an examples/cookbok section in the lucky guides with a similar example fulfill this request? It would also be nice to have this section of the guide provide an example flow spec for uploading.

[Amber image upload example](https://docs.amberframework.org/amber/cookbook/file-upload)

**Comment by jwoertink** [comment]
I haven't used file uploads in lucky yet, so I'm not sure how great the support is, but I think any sort of documentation would be better than what we have now, so it would all be welcomed. Maybe something that just shows a small example of taking a file from a file input to saving it locally on the file system. We could probably also add a guide of sending a file from your action to the user (like downloading a PDF or whatever).

**Comment by rnice01** [comment]
I'd like to work on this to provide a simple local file upload example.

**Comment by jwoertink** [comment]
Do it up! 👍
