### ISSUE TITLE
Add past Lucky videos to Awesome list

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#876]
The previous Crystal conferences had Lucky presentations. We should link to those under the "Blog Posts" section of the awesome list. Then we can rename that section to "Blog Posts and Videos" or something

**Comment by jwoertink** [comment]
https://www.se-radio.net/2020/09/episode-425-paul-smith-on-the-crystal-programming-language-and-the-lucky-web-framework/

**Comment by stephendolan** [comment]
https://www.youtube.com/watch?v=_gt5khId1AA&list=PLe1-A91ZPTpBBrrIV-N_fMmCWbFM4Uj4v&index=4

https://www.youtube.com/watch?v=a1n6bxToxqE&list=PLe1-A91ZPTpBBrrIV-N_fMmCWbFM4Uj4v&index=5&t=9s

https://www.youtube.com/watch?v=XRl-it1-ruI&list=PLe1-A91ZPTpBBrrIV-N_fMmCWbFM4Uj4v&index=9

**Comment by jwoertink** [comment]
Sweet! Thanks for digging those up
