### ISSUE TITLE
namespace prefix?

### ISSUE THREAD

**Issue by testbird** [luckyframework/website#90]
https://luckyframework.org/guides/http-and-routing/routing-and-params#namespaces-are-handled-automatically
> You can namespace your actions by creating subfolders like src/actions/admin/projects/index.cr.
> class Admin::Projects::Index < BrowserAction

Is it really the folder, or rather the Admin:: prefix of the class name?

**Comment by paulcsmith** [comment]
It is the class name. Nice catch

**Comment by testbird** [comment]
Ok, very good that relates to my comments at https://github.com/luckyframework/lucky/issues/642 then. (Good if files can get loaded regardless of how they are sorted into subfolders.)
