### ISSUE TITLE
Add the Lucky VS code extension to awesome

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#902]
The Lucky VS code extension is a great tool, so we should add it to the awesome list of tools

**Comment by stephendolan** [comment]
Love it! 😁

**Comment by stephendolan** [comment]
https://github.com/stephendolan/vscode-lucky

**Comment by stephendolan** [comment]
https://marketplace.visualstudio.com/items?itemName=stephendolan.lucky
