### ISSUE TITLE
Hotwire error triggering on HTML conversion

### ISSUE THREAD

**Issue by robcole** [luckyframework/website#947]
Replication: attempt to convert any HTML at https://luckyframework.org/html or `main` branch.

```
# Browser Console Error Log

Error: Form responses must redirect to another location
    at I.requestSucceededWithResponse (app.js?id=20f4d48f01b21bc54b91c52f76f76c03:2:12395)
    at j.receive (app.js?id=20f4d48f01b21bc54b91c52f76f76c03:2:7148)
```

Relevant issues:

https://github.com/hotwired/turbo/issues/22
https://github.com/hotwired/turbo/issues/73
https://github.com/hotwired/turbo/issues/375

**Comment by jwoertink** [comment]
oh, so it's turbo related? Maybe we need to go back to turbolinks for the time being? :thinking:

**Comment by robcole** [comment]
Yeah, I’m gonna take a poke at what it’d take to fix it first, and downgrade us if not.

**Comment by jwoertink** [comment]
Here's the PR where I changed it https://github.com/luckyframework/website/pull/932
