### ISSUE TITLE
Use pgcrypto instead of uuid-ossp

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#992]
The `pgcrypto` extension seems to be a little lighterweight, but also better maintained than `uuid-ossp`. More than likely, you just need UUID v4 generation, and the `pgcrypto` extension works great for that.

We need to update all mentions of `uuid-ossp` and any spot we might say `uuid_generate_v4()` with `pgcrypto` and `gen_random_uuid()`

**Comment by matthewmcgarvey** [comment]
The uuid feature of Avram depends on one of those doesn't it?

**Comment by jwoertink** [comment]
apparently we reference both :sweat_smile:
